package visualization;

import javafx.animation.Animation;
import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.application.Application;
import javafx.concurrent.Task;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.scene.canvas.GraphicsContext;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.Slider;
import javafx.scene.control.TextField;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.stage.Stage;
import javafx.util.Duration;
import simulation.Main;
import simulation.Simulation;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * JavaFX application that can both run the backend simulation and replay simulation logs as an interactive timeline.
 * <p>
 * Backend run workflow:
 * <ul>
 *     <li>User enters map and object counts.</li>
 *     <li>App calls {@link Main#configure(File, int, int, int, int, int)} to generate config.</li>
 *     <li>App constructs {@link Simulation} and runs {@link Simulation#simulate()} on a background thread.</li>
 *     <li>App reloads generated CSV logs and updates replay UI.</li>
 * </ul>
 */
public class SimulationReplayApp extends Application {

    /** Path to truck log generated by backend simulation. */
    private static final Path TRUCKS_FILE = Path.of("TrucksCSV.txt");
    /** Path to warehouse log generated by backend simulation. */
    private static final Path WAREHOUSES_FILE = Path.of("WarehousesCSV.txt");
    /** Path to shipment log generated by backend simulation. */
    private static final Path SHIPMENTS_FILE = Path.of("ShipmentsCSV.txt");
    /** Path to config file consumed by backend simulation. */
    private static final File CONFIG_FILE = new File("config.txt");

    private Canvas canvas;
    private Label hourLabel;
    private Label speedLabel;
    private Label statusLabel;
    private Slider hourSlider;
    private Slider speedSlider;
    private Button playPauseButton;

    private TextField mapXField;
    private TextField mapYField;
    private TextField warehousesField;
    private TextField shipmentsField;
    private TextField trucksField;
    private Button runSimulationButton;

    private ReplayData replayData;
    private Timeline timeline;
    private boolean sliderDragInProgress;
    private double playheadHour = 0.0;

    /**
     * Creates and displays the full window layout: backend controls, replay controls, and render canvas.
     */
    @Override
    public void start(Stage stage) {
        replayData = loadReplayData();

        BorderPane root = new BorderPane();
        root.setPadding(new Insets(12));

        canvas = new Canvas(1060, 670);
        root.setCenter(canvas);

        root.setTop(buildBackendControlPanel());
        root.setBottom(buildReplayControlPanel());

        setupTimeline();
        bindControls();
        drawInterpolatedFrame(0.0);

        Scene scene = new Scene(root, 1260, 930);
        stage.setTitle("Transport Simulation: Run + Replay Viewer");
        stage.setScene(scene);
        stage.show();
    }

    /**
     * Builds the top section that lets user configure and run the backend simulation directly from JavaFX.
     */
    private VBox buildBackendControlPanel() {
        Label title = new Label("Backend Simulation Controls");

        mapXField = createNumericField("400");
        mapYField = createNumericField("400");
        warehousesField = createNumericField("20");
        shipmentsField = createNumericField("60");
        trucksField = createNumericField("20");

        GridPane grid = new GridPane();
        grid.setHgap(10);
        grid.setVgap(8);
        grid.addRow(0, new Label("Map X (1-1000):"), mapXField,
                new Label("Map Y (1-1000):"), mapYField,
                new Label("Warehouses (2-5000):"), warehousesField);
        grid.addRow(1, new Label("Shipments (1-10000):"), shipmentsField,
                new Label("Trucks (1-5000):"), trucksField);

        runSimulationButton = new Button("Run Backend Simulation");
        runSimulationButton.setOnAction(e -> runBackendSimulation());

        Button reloadLogsButton = new Button("Reload Logs Only");
        reloadLogsButton.setOnAction(e -> {
            replayData = loadReplayData();
            resetReplayToStart();
            statusLabel.setText(replayData.message);
        });

        HBox actions = new HBox(10, runSimulationButton, reloadLogsButton);
        actions.setAlignment(Pos.CENTER_LEFT);

        VBox box = new VBox(8, title, grid, actions);
        box.setPadding(new Insets(0, 0, 8, 0));
        return box;
    }

    /**
     * Builds the bottom section that controls replay playback and shows status.
     */
    private VBox buildReplayControlPanel() {
        hourLabel = new Label("Hour: 0");
        speedLabel = new Label("Speed: 1.0x");
        statusLabel = new Label(replayData.message);

        hourSlider = new Slider(0, Math.max(0, replayData.maxHour), 0);
        hourSlider.setMajorTickUnit(Math.max(1, replayData.maxHour / 10.0));
        hourSlider.setMinorTickCount(0);
        hourSlider.setSnapToTicks(false);
        hourSlider.setPrefWidth(440);

        speedSlider = new Slider(0.25, 5.0, 1.0);
        speedSlider.setPrefWidth(160);

        playPauseButton = new Button("Play");
        playPauseButton.setOnAction(e -> togglePlayback());

        Button resetButton = new Button("Reset");
        resetButton.setOnAction(e -> resetReplayToStart());

        Button previousButton = new Button("◀ Prev");
        previousButton.setOnAction(e -> {
            timeline.stop();
            playPauseButton.setText("Play");
            playheadHour = Math.max(0, Math.floor(playheadHour) - 1);
            hourSlider.setValue(playheadHour);
            drawInterpolatedFrame(playheadHour);
        });

        Button nextButton = new Button("Next ▶");
        nextButton.setOnAction(e -> {
            timeline.stop();
            playPauseButton.setText("Play");
            playheadHour = Math.min(replayData.maxHour, Math.ceil(playheadHour) + 1);
            hourSlider.setValue(playheadHour);
            drawInterpolatedFrame(playheadHour);
        });

        HBox controls = new HBox(10,
                playPauseButton, previousButton, nextButton, resetButton,
                new Label("Timeline:"), hourSlider, hourLabel,
                new Label("Speed:"), speedSlider, speedLabel);
        controls.setAlignment(Pos.CENTER_LEFT);

        VBox box = new VBox(8, controls, statusLabel);
        box.setPadding(new Insets(8, 0, 0, 0));
        return box;
    }

    /**
     * Creates a standard numeric text field with starter value.
     */
    private TextField createNumericField(String value) {
        TextField tf = new TextField(value);
        tf.setPrefWidth(90);
        return tf;
    }

    /**
     * Runs config-generation + simulation on a background thread, then refreshes replay data.
     */
    private void runBackendSimulation() {
        int mapX;
        int mapY;
        int warehouses;
        int shipments;
        int trucks;

        try {
            mapX = Integer.parseInt(mapXField.getText().trim());
            mapY = Integer.parseInt(mapYField.getText().trim());
            warehouses = Integer.parseInt(warehousesField.getText().trim());
            shipments = Integer.parseInt(shipmentsField.getText().trim());
            trucks = Integer.parseInt(trucksField.getText().trim());
        } catch (NumberFormatException ex) {
            statusLabel.setText("Invalid numeric input. Please enter integers only.");
            return;
        }

        runSimulationButton.setDisable(true);
        statusLabel.setText("Running backend simulation... please wait.");

        Task<Void> runTask = new Task<>() {
            @Override
            protected Void call() {
                Main.configure(CONFIG_FILE, mapX, mapY, trucks, warehouses, shipments);
                Simulation simulation = new Simulation(CONFIG_FILE);
                simulation.simulate();
                return null;
            }
        };

        runTask.setOnSucceeded(event -> {
            replayData = loadReplayData();
            resetReplayToStart();
            statusLabel.setText("Simulation finished and replay reloaded successfully.");
            runSimulationButton.setDisable(false);
        });

        runTask.setOnFailed(event -> {
            Throwable error = runTask.getException();
            String message = error == null ? "Unknown failure while running simulation." : error.getMessage();
            statusLabel.setText("Simulation failed: " + message);
            runSimulationButton.setDisable(false);
        });

        Thread worker = new Thread(runTask, "simulation-runner");
        worker.setDaemon(true);
        worker.start();
    }

    /**
     * Re-initializes timeline position and slider bounds after loading new replay data.
     */
    private void resetReplayToStart() {
        timeline.stop();
        playPauseButton.setText("Play");
        playheadHour = 0.0;
        hourSlider.setMax(Math.max(0, replayData.maxHour));
        hourSlider.setMajorTickUnit(Math.max(1, replayData.maxHour / 10.0));
        hourSlider.setValue(0.0);
        drawInterpolatedFrame(0.0);
    }

    /**
     * Wires slider listeners for interactive scrubbing and speed display updates.
     */
    private void bindControls() {
        hourSlider.setOnMousePressed(e -> sliderDragInProgress = true);
        hourSlider.setOnMouseReleased(e -> {
            sliderDragInProgress = false;
            playheadHour = hourSlider.getValue();
            drawInterpolatedFrame(playheadHour);
        });

        hourSlider.valueProperty().addListener((obs, oldVal, newVal) -> {
            if (sliderDragInProgress) {
                playheadHour = newVal.doubleValue();
                drawInterpolatedFrame(playheadHour);
            }
        });

        speedSlider.valueProperty().addListener((obs, oldVal, newVal) ->
                speedLabel.setText(String.format("Speed: %.2fx", newVal.doubleValue())));
    }

    /**
     * Creates the periodic playback loop that advances the replay playhead.
     */
    private void setupTimeline() {
        timeline = new Timeline(new KeyFrame(Duration.millis(40), event -> {
            double deltaHours = speedSlider.getValue() * 0.06;
            playheadHour = Math.min(replayData.maxHour, playheadHour + deltaHours);
            hourSlider.setValue(playheadHour);
            drawInterpolatedFrame(playheadHour);

            if (playheadHour >= replayData.maxHour) {
                timeline.stop();
                playPauseButton.setText("Play");
            }
        }));
        timeline.setCycleCount(Animation.INDEFINITE);
    }

    /**
     * Starts or pauses playback; if replay ended, it restarts from hour 0.
     */
    private void togglePlayback() {
        if (timeline.getStatus() == Animation.Status.RUNNING) {
            timeline.stop();
            playPauseButton.setText("Play");
            return;
        }

        if (playheadHour >= replayData.maxHour) {
            playheadHour = 0.0;
            hourSlider.setValue(0.0);
            drawInterpolatedFrame(0.0);
        }

        timeline.play();
        playPauseButton.setText("Pause");
    }

    /**
     * Draws the map and entities at a fractional hour by interpolating truck positions between adjacent frame hours.
     */
    private void drawInterpolatedFrame(double hourPosition) {
        GraphicsContext gc = canvas.getGraphicsContext2D();
        gc.setFill(Color.rgb(20, 24, 35));
        gc.fillRect(0, 0, canvas.getWidth(), canvas.getHeight());

        int baseHour = (int) Math.floor(hourPosition);
        int nextHour = Math.min(replayData.maxHour, baseHour + 1);
        double t = hourPosition - baseHour;

        FrameState baseFrame = replayData.frames.getOrDefault(baseHour, new FrameState());
        FrameState nextFrame = replayData.frames.getOrDefault(nextHour, baseFrame);

        double width = canvas.getWidth();
        double height = canvas.getHeight();
        double leftPad = 60;
        double topPad = 40;
        double mapW = width - (leftPad * 2);
        double mapH = height - (topPad * 2);

        gc.setStroke(Color.rgb(90, 105, 135));
        gc.setLineWidth(2.0);
        gc.strokeRect(leftPad, topPad, mapW, mapH);

        for (WarehouseState warehouse : baseFrame.warehouses.values()) {
            double x = leftPad + (warehouse.posX / replayData.mapX) * mapW;
            double y = topPad + (warehouse.posY / replayData.mapY) * mapH;
            gc.setFill(Color.web("#5ca9ff"));
            gc.fillOval(x - 8, y - 8, 16, 16);
            gc.setFill(Color.WHITE);
            gc.fillText("W" + warehouse.id, x + 10, y - 6);
        }

        for (TruckState currentTruck : baseFrame.trucks.values()) {
            TruckState nextTruck = nextFrame.trucks.getOrDefault(currentTruck.id, currentTruck);
            double lerpX = currentTruck.posX + ((nextTruck.posX - currentTruck.posX) * t);
            double lerpY = currentTruck.posY + ((nextTruck.posY - currentTruck.posY) * t);
            double x = leftPad + (lerpX / replayData.mapX) * mapW;
            double y = topPad + (lerpY / replayData.mapY) * mapH;

            gc.setFill(statusColor(currentTruck.status));
            gc.fillRect(x - 6, y - 6, 12, 12);
            gc.setFill(Color.WHITE);
            gc.fillText("T" + currentTruck.id, x + 8, y - 8);
        }

        int delivered = 0;
        for (ShipmentState shipment : baseFrame.shipments.values()) {
            if ("Delivered".equalsIgnoreCase(shipment.status)) {
                delivered++;
            }
        }

        gc.setFill(Color.WHITE);
        gc.fillText("Warehouses: " + baseFrame.warehouses.size(), 20, 20);
        gc.fillText("Trucks: " + baseFrame.trucks.size(), 165, 20);
        gc.fillText("Delivered: " + delivered + "/" + baseFrame.shipments.size(), 270, 20);

        hourLabel.setText(String.format("Hour: %.2f / %d", hourPosition, replayData.maxHour));
    }

    /**
     * Maps textual truck statuses to display colors.
     */
    private Color statusColor(String status) {
        if (status == null) return Color.GRAY;
        String normalized = status.trim().toLowerCase();
        if (normalized.contains("done")) return Color.LIMEGREEN;
        if (normalized.contains("wait")) return Color.GOLD;
        if (normalized.contains("move") || normalized.contains("travel")) return Color.ORANGE;
        return Color.CORNFLOWERBLUE;
    }

    /**
     * Loads and parses CSV log files into per-hour frame structures.
     */
    private ReplayData loadReplayData() {
        try {
            List<String> truckLines = Files.readAllLines(TRUCKS_FILE);
            List<String> warehouseLines = Files.readAllLines(WAREHOUSES_FILE);
            List<String> shipmentLines = Files.readAllLines(SHIPMENTS_FILE);

            Map<Integer, FrameState> frames = new HashMap<>();
            Set<Integer> allHours = new HashSet<>();
            double maxX = 1.0;
            double maxY = 1.0;

            for (int i = 1; i < warehouseLines.size(); i++) {
                String[] cols = warehouseLines.get(i).split(",", -1);
                int hour = parseInt(cols, 0);
                int id = parseInt(cols, 1);
                double posX = parseDouble(cols, 2);
                double posY = parseDouble(cols, 3);
                int invSize = parseInt(cols, 7);

                maxX = Math.max(maxX, posX);
                maxY = Math.max(maxY, posY);
                FrameState frame = frames.computeIfAbsent(hour, k -> new FrameState());
                frame.warehouses.put(id, new WarehouseState(id, posX, posY, invSize));
                allHours.add(hour);
            }

            for (int i = 1; i < truckLines.size(); i++) {
                String[] cols = truckLines.get(i).split(",", -1);
                int hour = parseInt(cols, 0);
                int id = parseInt(cols, 1);
                double posX = parseDouble(cols, 2);
                double posY = parseDouble(cols, 3);
                String status = cols.length > 6 ? cols[6] : "";

                maxX = Math.max(maxX, posX);
                maxY = Math.max(maxY, posY);
                FrameState frame = frames.computeIfAbsent(hour, k -> new FrameState());
                frame.trucks.put(id, new TruckState(id, posX, posY, status));
                allHours.add(hour);
            }

            for (int i = 1; i < shipmentLines.size(); i++) {
                String[] cols = shipmentLines.get(i).split(",", -1);
                int hour = parseInt(cols, 0);
                int id = parseInt(cols, 1);
                String status = cols.length > 6 ? cols[6] : "";

                FrameState frame = frames.computeIfAbsent(hour, k -> new FrameState());
                frame.shipments.put(id, new ShipmentState(id, status));
                allHours.add(hour);
            }

            if (allHours.isEmpty()) {
                return ReplayData.empty("No replay rows found in CSV files.");
            }

            int maxHour = Collections.max(allHours);
            for (int hour = 0; hour <= maxHour; hour++) {
                frames.computeIfAbsent(hour, k -> new FrameState());
            }

            return new ReplayData(frames, maxHour, maxX, maxY,
                    "Logs loaded. You can run backend again or replay existing results.");
        } catch (IOException ex) {
            return ReplayData.empty("Logs not found. Run backend simulation from this screen first.");
        }
    }

    /** Parses an integer CSV cell safely with empty-cell fallback. */
    private int parseInt(String[] cols, int idx) {
        if (idx >= cols.length || cols[idx].isBlank()) return 0;
        return Integer.parseInt(cols[idx].trim());
    }

    /** Parses a double CSV cell safely with empty-cell fallback. */
    private double parseDouble(String[] cols, int idx) {
        if (idx >= cols.length || cols[idx].isBlank()) return 0.0;
        return Double.parseDouble(cols[idx].trim());
    }

    /** Standard JavaFX launcher entry point. */
    public static void main(String[] args) {
        launch(args);
    }

    /**
     * Immutable replay container used by rendering + playback controls.
     */
    private static class ReplayData {
        final Map<Integer, FrameState> frames;
        final int maxHour;
        final double mapX;
        final double mapY;
        final String message;

        ReplayData(Map<Integer, FrameState> frames, int maxHour, double mapX, double mapY, String message) {
            this.frames = frames;
            this.maxHour = maxHour;
            this.mapX = mapX;
            this.mapY = mapY;
            this.message = message;
        }

        static ReplayData empty(String message) {
            Map<Integer, FrameState> frames = new HashMap<>();
            frames.put(0, new FrameState());
            return new ReplayData(frames, 0, 1.0, 1.0, message);
        }
    }

    /**
     * Hour-level state snapshot parsed from CSV files.
     */
    private static class FrameState {
        final Map<Integer, WarehouseState> warehouses = new HashMap<>();
        final Map<Integer, TruckState> trucks = new HashMap<>();
        final Map<Integer, ShipmentState> shipments = new HashMap<>();
    }

    /** Warehouse render state parsed from warehouse CSV. */
    private record WarehouseState(int id, double posX, double posY, int inventorySize) {}
    /** Truck render state parsed from truck CSV. */
    private record TruckState(int id, double posX, double posY, String status) {}
    /** Shipment status state parsed from shipment CSV. */
    private record ShipmentState(int id, String status) {}
}
